### ISSUE TITLE
Failed installation on OS X

### ISSUE THREAD

**Issue by vinkla** [viddo/recent-files-fuzzy-finder#14] opened 2015-12-02 12:21 UTC
Tried installing this package in Atom 1.2.4 on OS X 10.11.1 but it failed?

<img width="693" alt="screen shot 2015-12-02 at 1 20 13 pm" src="https://cloud.githubusercontent.com/assets/499192/11530732/72918b4e-98f7-11e5-9f43-52894e19af59.png">

**Comment by viddo** [comment] 2015-12-02 13:38
Can you reproduce it? If yes, can you paste here what's displayed under  _"Show output…"_? It's hard to tell what's wrong without more to go on :confused:

**Comment by vinkla** [comment] 2015-12-02 14:40
I can reproduce it, here is my output:
1. https://vink.la/ag0UcW9
2. https://vink.la/B1AzSr4

Doesn't seem to be able to copy/paste the output.

**Comment by viddo** [comment] 2015-12-03 08:04
A dependency was updated [just recently](12) that requires a [recent version of atom (1.2.0)](https://github.com/viddo/recent-files-fuzzy-finder/blob/a134550dd944142588c68ff24b6678342027463a/package.json#L9), this dependency have some native bindings that needs to be built on install, looking at the stack trace from the output you pasted it seems to be running using an older version of atom (1.0.19) to build it which fails for some reason.

Could you try to update the cask install of atom and retry the install to see if that solves it?

**Comment by vinkla** [comment] 2015-12-03 08:29
Thanks for getting back. Are you referring to the folder name? If so, in the current flow of Homebrew Cask they don't update the version folder even though I update the application https://vink.la/80zInv2

**Comment by viddo** [comment] 2015-12-03 09:39
Ah ok, I misinterpreted that then.

I've been trying to reproduce your scenario but nothing so far. I'm still on Yosemite 10.10.5 though, so I guess it's possible that the CLI tools differs.

Anyway, I've been planning on removing that dependency to avoid headaches like this, so far it have only created more headaches than it solves… unfortunately won't have time for another week or so. :(

**Comment by vinkla** [comment] 2015-12-03 09:47
Okay, no worries. Let me know how it goes :)

**Comment by viddo** [comment] 2015-12-04 22:36
Should be [fixed now](https://github.com/viddo/recent-files-fuzzy-finder/commit/53a6b4f55544f9fea0c9fc5cdb9ca7706f74a2da), as of v0.2.3

**Closed by viddo** 2015-12-04 22:36 UTC

**Comment by vinkla** [comment] 2015-12-04 22:52
Thanks, now it works much better!
